### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by jsathu07** [jsathu07/EduChange#23]
Change the animation into something
Related to loading user needs to know that the app is loading
This animation doesn't show that it is loading 
Try to add something related to spinner

**Comment by rsibishan** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/54585836/107842793-de584100-6deb-11eb-80b8-bbf99dc2f315.png">

How does this look ⏳

**Comment by jsathu07** [comment]
looking good change it
